services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    platform: linux/amd64
    container_name: seo-rank-tracker-local
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LocalDbPassword123
    ports:
      - "1433:1433"
    volumes:
      - ./temp/sqlserver_data:/var/opt/mssql/data

  seoranktracker.infrastructure.dbup:
    image: seoranktracker.infrastructure.dbup
    build:
      context: ./src
      dockerfile: SeoRankTracker.Infrastructure.DbUp/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SeoRankTracker;User Id=sa;Password=LocalDbPassword123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  seoranktracker.api:
    image: seoranktracker.api
    build:
      context: ./src
      dockerfile: SeoRankTracker.API/Dockerfile
    ports:
      - "5163:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SeoRankTracker;User Id=sa;Password=LocalDbPassword123;TrustServerCertificate=True;
    depends_on:
      - seoranktracker.infrastructure.dbup