@SeoRankTracker.API_HostAddress = http://localhost:5163

@searchKeyword = land registry searches
@website = www.infotrack.co.uk

GET {{SeoRankTracker.API_HostAddress}}/api/website-ranks?searchKeyword={{searchKeyword}}&websiteUrl={{website}}
Accept: application/json
###

GET {{SeoRankTracker.API_HostAddress}}/api/website-ranks/highest-per-day?searchKeyword={{searchKeyword}}&websiteUrl={{website}}
Accept: application/json
###

GET {{SeoRankTracker.API_HostAddress}}/api/website-ranks/unique-search-history
Accept: application/json
###

